weather_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: dremio  
      port: 31010   
      user: admin
      password: admin
      dbname: Dremio
      schema: your_schema