version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: weather_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dremio:
    image: dremio/dremio-oss:24.0
    ports:
      - "9047:9047"
      - "31010:31010"
    volumes:
      - dremio_data:/opt/dremio/data

  dbt:
    image: fishtownanalytics/dbt:1.0.0
    volumes:
      - ./dbt:/usr/app/dbt
    working_dir: /usr/app/dbt
    depends_on:
      - dremio

volumes:
  minio_data:
  postgres_data:
  dremio_data: